
import "./globals.css";


import localFont from 'next/font/local';

const monaSans = localFont({
  src: [
    { path: '../public/fonts/MonaSans-Regular.woff2', weight: '400' },
    { path: '../public/fonts/MonaSans-Medium.woff2', weight: '500' },
    { path: '../public/fonts/MonaSans-SemiBold.woff2', weight: '600' },
    { path: '../public/fonts/MonaSans-Bold.woff2', weight: '700' },
  ],
  variable: '--font-mona',
    display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
  <html lang="en" className={monaSans.variable}>
      <body>

        {children}
      </body>
    </html>
  );
}
